#server:
#  port: 8212
#spring:
#  application:
#    name: service-provider-two  #service-provider-one nacos将服务服务注册中心，默认采用应用程序名称。如果两个服务名称一样，网关会采用负载均衡。默认轮训
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
##        metadata:  #以下是springbootadmin的配置
##          management:
##            context-path: '${server.servlet.context-path}/actuator'
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'