#server:
#  port: 8212
#
#spring:
#  application:
#    name: service-provider-two  #service-provider-one nacos将服务服务注册中心，默认采用应用程序名称。如果两个服务名称一样，网关会采用负载均衡。默认轮训
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
##        metadata:  #以下是springbootadmin的配置
##          management:
##            context-path: '${server.servlet.context-path}/actuator'
#
#  datasource:
#    #mysql
#    #具体参见类DynamicDataSourceAspect 说明
#    #不用此默认，默认就是写库,多数据源用jdbcUrl，不是url,spring 默认用的是url，用多数据源用url会报错。
#    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#
#    # HikariCP： springboot2.0 默认的连接池。https://github.com/brettwooldridge/HikariCP
#    #HikariCP  高并发性能优。mysql 8h 空闲断开连接可用quartz 调度定期select 1  。
#    #产生此问题DB工作就不繁忙，性能要求不高。可以用上面dbcp2的配置，采取空闲查询策略。
#    #要引入mybatis
#    type: com.zaxxer.hikari.HikariDataSource
#    # Hikari will use the above plus the following to setup connection pooling
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 100
#      auto-commit: true #OrderManagerService 代码异常，spring自动回滚，或者手动回滚。否则正常自动提交
#      idle-timeout: 60000
#      #pool-name: HikariCP-Demo
#      max-lifetime: 1800000
#      connection-timeout: 600000
#      #connection-test-query: SELECT 1
#
#  redis:
#    ##单机
#    #  数据库索引
#    database: 0
#
#    #    单机
#    # 远程服务器地址
#    host: 127.0.0.1
#    # 远程服务器端口
#    port: 6379
#
#
#    #    #配置集群，自动写入集群
#    #    ##集群 注意：密码用上面密码配置 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006 #集群节点
#    #    cluster:
#    #      nodes:
#    #        - 127.0.0.1:7000
#    #        - 127.0.0.1:7001
#    #        - 127.0.0.1:7002
#    #        - 127.0.0.1:7003
#    #        - 127.0.0.1:7004
#    #        - 127.0.0.1:7005
#    #      max-redirects: 3
#
#
#    # 集群配置也用此处写正确的密码
#    password: fancky123456
#    # 链接超时时间（毫秒）
#    timeout: 30000
#
#    #redis连接池 lettuce、jedis。连接池 单机配置。默认集成lettuce
#    #    jedis:
#    lettuce:
#      pool:
#        # 最大空闲连接
#        max-idle: 64
#        # 最小空闲链接
#        min-idle: 0
#        # 最大连接数（负数表示没有限制）
#        max-active: 64
#        # 最大阻塞等待时间（负数表示没有限制）
#        max-wait: 0
#
#
#    #    ##集群 注意：密码用上面密码配置
#    #    cluster:
#    #      nodes:
#    #        - 127.0.0.1:7000
#    #        - 127.0.0.1:7001
#    #        - 127.0.0.1:7002
#    #        - 127.0.0.1:7003
#    #        - 127.0.0.1:7004
#    #      max-redirects: 3
#
#    #    ##哨兵 密码用上面密码配置
#    #    sentinel:
#    #      master: mymaster
#    #      nodes:
#    #        - 127.0.0.1:60001
#    #        - 127.0.0.1:60002
#    #        - 127.0.0.1:60003
#
#
#    #springboot 配置未成功，参见代码的配置
#    redisson:
#      file: classpath:redisson-config.yml
#
##springboot 监控 Actuator
##management:
##  endpoints:
##    web:
##      exposure:
##        include: '*'
#
##配置控制台打印sql语句 。mybatis plus 默认打印日志到控制台，不打印到日志文件。
##mybatis-plus:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#logging:
#  config: classpath:log4j2.xml