server:
  port: 8210
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

service:
  provider-one: service-provider-one

config:
  appName: product_test

#logging:
#  config: classpath:log4j2.xml


